[package]
name = "downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.20", features = ["cookies", "blocking", "rustls-tls"] }
tokio = { version = "1.45.1", features = ["full"] }
dotenv = "0.15.0"
